/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IKIP17Burnable,
  IKIP17BurnableInterface,
} from "../../../../contracts/TestTokens/Test_OwnableKIP17.sol/IKIP17Burnable";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IKIP17Burnable__factory {
  static readonly abi = _abi;
  static createInterface(): IKIP17BurnableInterface {
    return new utils.Interface(_abi) as IKIP17BurnableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKIP17Burnable {
    return new Contract(address, _abi, signerOrProvider) as IKIP17Burnable;
  }
}
