/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IKIP17Receiver,
  IKIP17ReceiverInterface,
} from "../../../../contracts/TestTokens/Test_OwnableKIP17.sol/IKIP17Receiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onKIP17Received",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IKIP17Receiver__factory {
  static readonly abi = _abi;
  static createInterface(): IKIP17ReceiverInterface {
    return new utils.Interface(_abi) as IKIP17ReceiverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKIP17Receiver {
    return new Contract(address, _abi, signerOrProvider) as IKIP17Receiver;
  }
}
