/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as testErc721EumerableSol from "./Test_ERC721Eumerable.sol";
export type { testErc721EumerableSol };
import type * as testOwnableKip17Sol from "./Test_OwnableKIP17.sol";
export type { testOwnableKip17Sol };
