spring:
#  env ?? ??
  config:
    import: optional:file:.env[.properties]
#   DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/undefined?serverTimezone=Asia/Seoul
    username: undefined
    password: undefined
#   jpa
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      jdbc:
        time-zone: Asia/Seoul
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect