spring:
  #  DB
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test
    username: test
    password: test
    driver-class-name: org.h2.Driver

  #  env파일 설정
  config:
    import: optional:file:.env[.properties]
  #   Jpa
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      jdbc:
        time-zone: Asia/Seoul
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      hibernate:
        format_sql: true
  #   flyway
  flyway:
    enabled: false
  #   sql
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

# uri

uri:
  contract-address: ${CONTRACT_ADDRESS}
  websocket-uri: ${WEBSOCKET_URI}
  http-rpc-uri: ${HTTP_RPC_URI}

# wallet

wallet:
  private-key: ${PRIVATE_KEY}
  public-key: ${PUBLIC_KEY}