/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interface from "./Interface";
export type { interface };
export type { Undefined } from "./Undefined";
export type { UndefinedConfig } from "./UndefinedConfig";
