/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface UndefinedInterface extends utils.Interface {
  functions: {
    "buyTickets(uint96,uint16)": FunctionFragment;
    "buyer(uint256,uint256)": FunctionFragment;
    "chooseWinner(uint96,uint256)": FunctionFragment;
    "claimAllNfts()": FunctionFragment;
    "claimBalance(uint256)": FunctionFragment;
    "claimNftByIndex(uint256)": FunctionFragment;
    "claimNftForFailedSeller(uint96)": FunctionFragment;
    "claimableBalance(address)": FunctionFragment;
    "claimableNft(address,uint256)": FunctionFragment;
    "creatorInfo(address)": FunctionFragment;
    "deListNft(address)": FunctionFragment;
    "feeBox()": FunctionFragment;
    "feeNumerator()": FunctionFragment;
    "feeTo()": FunctionFragment;
    "getClaimableNftsLength(address)": FunctionFragment;
    "getTicketOwnerByIndex(uint256,uint256)": FunctionFragment;
    "initialize(uint16,uint16,uint96,address)": FunctionFragment;
    "isListed(address)": FunctionFragment;
    "listNft(address,address,uint8)": FunctionFragment;
    "listNft(address)": FunctionFragment;
    "maxTicketAmount()": FunctionFragment;
    "minTicketPrice()": FunctionFragment;
    "onERC721Received(address,address,uint256,bytes)": FunctionFragment;
    "owner()": FunctionFragment;
    "raffles(uint256)": FunctionFragment;
    "registerRaffle(address,uint256,uint16,uint144,uint256)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setCreatorInfo(address,address,uint8)": FunctionFragment;
    "setFeeNumerator(uint16)": FunctionFragment;
    "setFeeTo(address)": FunctionFragment;
    "setMaxTicketAmount(uint16)": FunctionFragment;
    "setMinTicketPrice(uint96)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "withdrawFee(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "buyTickets"
      | "buyer"
      | "chooseWinner"
      | "claimAllNfts"
      | "claimBalance"
      | "claimNftByIndex"
      | "claimNftForFailedSeller"
      | "claimableBalance"
      | "claimableNft"
      | "creatorInfo"
      | "deListNft"
      | "feeBox"
      | "feeNumerator"
      | "feeTo"
      | "getClaimableNftsLength"
      | "getTicketOwnerByIndex"
      | "initialize"
      | "isListed"
      | "listNft(address,address,uint8)"
      | "listNft(address)"
      | "maxTicketAmount"
      | "minTicketPrice"
      | "onERC721Received"
      | "owner"
      | "raffles"
      | "registerRaffle"
      | "renounceOwnership"
      | "setCreatorInfo"
      | "setFeeNumerator"
      | "setFeeTo"
      | "setMaxTicketAmount"
      | "setMinTicketPrice"
      | "transferOwnership"
      | "withdrawFee"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "buyTickets",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "buyer",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "chooseWinner",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "claimAllNfts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimBalance",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "claimNftByIndex",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "claimNftForFailedSeller",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "claimableBalance",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "claimableNft",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorInfo",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "deListNft",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "feeBox", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "feeNumerator",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "feeTo", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getClaimableNftsLength",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getTicketOwnerByIndex",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isListed",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "listNft(address,address,uint8)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "listNft(address)",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "maxTicketAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minTicketPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "raffles",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "registerRaffle",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setCreatorInfo",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeNumerator",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeTo",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxTicketAmount",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinTicketPrice",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "buyTickets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "chooseWinner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimAllNfts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimNftByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimNftForFailedSeller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimableBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimableNft",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creatorInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deListNft", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "feeBox", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeNumerator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getClaimableNftsLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTicketOwnerByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isListed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "listNft(address,address,uint8)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listNft(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxTicketAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minTicketPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "raffles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerRaffle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCreatorInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeNumerator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFeeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMaxTicketAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinTicketPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFee",
    data: BytesLike
  ): Result;

  events: {
    "BuyTickets(uint256,address,uint256,uint256,uint256)": EventFragment;
    "ChooseWinner(uint256,address,uint256,uint256)": EventFragment;
    "ClaimAllNfts(address,uint256[])": EventFragment;
    "ClaimBalance(address,uint256,uint256)": EventFragment;
    "ClaimNft(address,uint256)": EventFragment;
    "DeListNft(address)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "ListNft(address,address,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "RegisterRaffle(uint256,uint256,address,uint256,uint256,uint256,address)": EventFragment;
    "SetCreatorInfo(address,uint256)": EventFragment;
    "SetFeeNumerator(uint256)": EventFragment;
    "SetMaxTicketAmount(uint256)": EventFragment;
    "SetMinTicketPrice(uint256)": EventFragment;
    "WithdrawFee(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BuyTickets"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ChooseWinner"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ClaimAllNfts"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ClaimBalance"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ClaimNft"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DeListNft"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ListNft"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RegisterRaffle"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetCreatorInfo"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetFeeNumerator"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetMaxTicketAmount"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetMinTicketPrice"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawFee"): EventFragment;
}

export interface BuyTicketsEventObject {
  raffleId: BigNumber;
  buyer: string;
  fromIndex: BigNumber;
  toIndex: BigNumber;
  leftTickets: BigNumber;
}
export type BuyTicketsEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber, BigNumber],
  BuyTicketsEventObject
>;

export type BuyTicketsEventFilter = TypedEventFilter<BuyTicketsEvent>;

export interface ChooseWinnerEventObject {
  raffleId: BigNumber;
  winner: string;
  winnerTicketIndex: BigNumber;
  settlement: BigNumber;
}
export type ChooseWinnerEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber],
  ChooseWinnerEventObject
>;

export type ChooseWinnerEventFilter = TypedEventFilter<ChooseWinnerEvent>;

export interface ClaimAllNftsEventObject {
  claimer: string;
  raffleIds: BigNumber[];
}
export type ClaimAllNftsEvent = TypedEvent<
  [string, BigNumber[]],
  ClaimAllNftsEventObject
>;

export type ClaimAllNftsEventFilter = TypedEventFilter<ClaimAllNftsEvent>;

export interface ClaimBalanceEventObject {
  claimer: string;
  amount: BigNumber;
  afterBalance: BigNumber;
}
export type ClaimBalanceEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  ClaimBalanceEventObject
>;

export type ClaimBalanceEventFilter = TypedEventFilter<ClaimBalanceEvent>;

export interface ClaimNftEventObject {
  claimer: string;
  raffleId: BigNumber;
}
export type ClaimNftEvent = TypedEvent<
  [string, BigNumber],
  ClaimNftEventObject
>;

export type ClaimNftEventFilter = TypedEventFilter<ClaimNftEvent>;

export interface DeListNftEventObject {
  nftCa: string;
}
export type DeListNftEvent = TypedEvent<[string], DeListNftEventObject>;

export type DeListNftEventFilter = TypedEventFilter<DeListNftEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface ListNftEventObject {
  nftCa: string;
  creator: string;
  creatorFeeNumerator: BigNumber;
}
export type ListNftEvent = TypedEvent<
  [string, string, BigNumber],
  ListNftEventObject
>;

export type ListNftEventFilter = TypedEventFilter<ListNftEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface RegisterRaffleEventObject {
  raffleId: BigNumber;
  tokenId: BigNumber;
  nftCa: string;
  ticketPrice: BigNumber;
  totalTickets: BigNumber;
  endTime: BigNumber;
  seller: string;
}
export type RegisterRaffleEvent = TypedEvent<
  [BigNumber, BigNumber, string, BigNumber, BigNumber, BigNumber, string],
  RegisterRaffleEventObject
>;

export type RegisterRaffleEventFilter = TypedEventFilter<RegisterRaffleEvent>;

export interface SetCreatorInfoEventObject {
  creator: string;
  creatorFeeNumerator: BigNumber;
}
export type SetCreatorInfoEvent = TypedEvent<
  [string, BigNumber],
  SetCreatorInfoEventObject
>;

export type SetCreatorInfoEventFilter = TypedEventFilter<SetCreatorInfoEvent>;

export interface SetFeeNumeratorEventObject {
  feeNumerator: BigNumber;
}
export type SetFeeNumeratorEvent = TypedEvent<
  [BigNumber],
  SetFeeNumeratorEventObject
>;

export type SetFeeNumeratorEventFilter = TypedEventFilter<SetFeeNumeratorEvent>;

export interface SetMaxTicketAmountEventObject {
  amount: BigNumber;
}
export type SetMaxTicketAmountEvent = TypedEvent<
  [BigNumber],
  SetMaxTicketAmountEventObject
>;

export type SetMaxTicketAmountEventFilter =
  TypedEventFilter<SetMaxTicketAmountEvent>;

export interface SetMinTicketPriceEventObject {
  price: BigNumber;
}
export type SetMinTicketPriceEvent = TypedEvent<
  [BigNumber],
  SetMinTicketPriceEventObject
>;

export type SetMinTicketPriceEventFilter =
  TypedEventFilter<SetMinTicketPriceEvent>;

export interface WithdrawFeeEventObject {
  to: string;
  amount: BigNumber;
}
export type WithdrawFeeEvent = TypedEvent<
  [string, BigNumber],
  WithdrawFeeEventObject
>;

export type WithdrawFeeEventFilter = TypedEventFilter<WithdrawFeeEvent>;

export interface Undefined extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: UndefinedInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    buyTickets(
      raffleId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    buyer(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    chooseWinner(
      raffleId: PromiseOrValue<BigNumberish>,
      salt: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    claimAllNfts(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    claimBalance(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    claimNftByIndex(
      index: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    claimNftForFailedSeller(
      raffleId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    claimableBalance(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    claimableNft(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber] & {
        raffleId: BigNumber;
        nftCa: string;
        tokenId: BigNumber;
      }
    >;

    creatorInfo(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, number] & { creator: string; creatorFeeNumerator: number }
    >;

    deListNft(
      nftCa: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    feeBox(overrides?: CallOverrides): Promise<[BigNumber]>;

    feeNumerator(overrides?: CallOverrides): Promise<[number]>;

    feeTo(overrides?: CallOverrides): Promise<[string]>;

    getClaimableNftsLength(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { length: BigNumber }>;

    getTicketOwnerByIndex(
      raffleId: PromiseOrValue<BigNumberish>,
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    initialize(
      feeNumerator_: PromiseOrValue<BigNumberish>,
      maxTicketAmount_: PromiseOrValue<BigNumberish>,
      minTicketPrice_: PromiseOrValue<BigNumberish>,
      feeTo_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isListed(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "listNft(address,address,uint8)"(
      nftCa: PromiseOrValue<string>,
      creator: PromiseOrValue<string>,
      creatorFeeNumerator: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "listNft(address)"(
      nftCa: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    maxTicketAmount(overrides?: CallOverrides): Promise<[number]>;

    minTicketPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    onERC721Received(
      operator: PromiseOrValue<string>,
      from: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    raffles(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        number,
        number,
        string,
        BigNumber,
        BigNumber,
        string,
        string
      ] & {
        raffleId: BigNumber;
        ticketPrice: BigNumber;
        totalTickets: number;
        leftTickets: number;
        nftCa: string;
        tokenId: BigNumber;
        endTime: BigNumber;
        seller: string;
        winner: string;
      }
    >;

    registerRaffle(
      nftCa: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      totalTickets: PromiseOrValue<BigNumberish>,
      ticketPrice: PromiseOrValue<BigNumberish>,
      minute: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setCreatorInfo(
      nftCa: PromiseOrValue<string>,
      creator: PromiseOrValue<string>,
      creatorFeeNumerator: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setFeeNumerator(
      feeNumerator_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setFeeTo(
      feeTo_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMaxTicketAmount(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMinTicketPrice(
      price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawFee(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  buyTickets(
    raffleId: PromiseOrValue<BigNumberish>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  buyer(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  chooseWinner(
    raffleId: PromiseOrValue<BigNumberish>,
    salt: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  claimAllNfts(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  claimBalance(
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  claimNftByIndex(
    index: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  claimNftForFailedSeller(
    raffleId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  claimableBalance(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  claimableNft(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, BigNumber] & {
      raffleId: BigNumber;
      nftCa: string;
      tokenId: BigNumber;
    }
  >;

  creatorInfo(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [string, number] & { creator: string; creatorFeeNumerator: number }
  >;

  deListNft(
    nftCa: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  feeBox(overrides?: CallOverrides): Promise<BigNumber>;

  feeNumerator(overrides?: CallOverrides): Promise<number>;

  feeTo(overrides?: CallOverrides): Promise<string>;

  getClaimableNftsLength(
    owner: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTicketOwnerByIndex(
    raffleId: PromiseOrValue<BigNumberish>,
    index: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  initialize(
    feeNumerator_: PromiseOrValue<BigNumberish>,
    maxTicketAmount_: PromiseOrValue<BigNumberish>,
    minTicketPrice_: PromiseOrValue<BigNumberish>,
    feeTo_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isListed(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "listNft(address,address,uint8)"(
    nftCa: PromiseOrValue<string>,
    creator: PromiseOrValue<string>,
    creatorFeeNumerator: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "listNft(address)"(
    nftCa: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  maxTicketAmount(overrides?: CallOverrides): Promise<number>;

  minTicketPrice(overrides?: CallOverrides): Promise<BigNumber>;

  onERC721Received(
    operator: PromiseOrValue<string>,
    from: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    data: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  raffles(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      number,
      number,
      string,
      BigNumber,
      BigNumber,
      string,
      string
    ] & {
      raffleId: BigNumber;
      ticketPrice: BigNumber;
      totalTickets: number;
      leftTickets: number;
      nftCa: string;
      tokenId: BigNumber;
      endTime: BigNumber;
      seller: string;
      winner: string;
    }
  >;

  registerRaffle(
    nftCa: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    totalTickets: PromiseOrValue<BigNumberish>,
    ticketPrice: PromiseOrValue<BigNumberish>,
    minute: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setCreatorInfo(
    nftCa: PromiseOrValue<string>,
    creator: PromiseOrValue<string>,
    creatorFeeNumerator: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setFeeNumerator(
    feeNumerator_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setFeeTo(
    feeTo_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMaxTicketAmount(
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMinTicketPrice(
    price: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawFee(
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    buyTickets(
      raffleId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    buyer(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    chooseWinner(
      raffleId: PromiseOrValue<BigNumberish>,
      salt: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    claimAllNfts(overrides?: CallOverrides): Promise<void>;

    claimBalance(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    claimNftByIndex(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    claimNftForFailedSeller(
      raffleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    claimableBalance(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimableNft(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber] & {
        raffleId: BigNumber;
        nftCa: string;
        tokenId: BigNumber;
      }
    >;

    creatorInfo(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [string, number] & { creator: string; creatorFeeNumerator: number }
    >;

    deListNft(
      nftCa: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    feeBox(overrides?: CallOverrides): Promise<BigNumber>;

    feeNumerator(overrides?: CallOverrides): Promise<number>;

    feeTo(overrides?: CallOverrides): Promise<string>;

    getClaimableNftsLength(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTicketOwnerByIndex(
      raffleId: PromiseOrValue<BigNumberish>,
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    initialize(
      feeNumerator_: PromiseOrValue<BigNumberish>,
      maxTicketAmount_: PromiseOrValue<BigNumberish>,
      minTicketPrice_: PromiseOrValue<BigNumberish>,
      feeTo_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    isListed(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "listNft(address,address,uint8)"(
      nftCa: PromiseOrValue<string>,
      creator: PromiseOrValue<string>,
      creatorFeeNumerator: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    "listNft(address)"(
      nftCa: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    maxTicketAmount(overrides?: CallOverrides): Promise<number>;

    minTicketPrice(overrides?: CallOverrides): Promise<BigNumber>;

    onERC721Received(
      operator: PromiseOrValue<string>,
      from: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    raffles(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        number,
        number,
        string,
        BigNumber,
        BigNumber,
        string,
        string
      ] & {
        raffleId: BigNumber;
        ticketPrice: BigNumber;
        totalTickets: number;
        leftTickets: number;
        nftCa: string;
        tokenId: BigNumber;
        endTime: BigNumber;
        seller: string;
        winner: string;
      }
    >;

    registerRaffle(
      nftCa: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      totalTickets: PromiseOrValue<BigNumberish>,
      ticketPrice: PromiseOrValue<BigNumberish>,
      minute: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setCreatorInfo(
      nftCa: PromiseOrValue<string>,
      creator: PromiseOrValue<string>,
      creatorFeeNumerator: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setFeeNumerator(
      feeNumerator_: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setFeeTo(
      feeTo_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setMaxTicketAmount(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setMinTicketPrice(
      price: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawFee(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "BuyTickets(uint256,address,uint256,uint256,uint256)"(
      raffleId?: PromiseOrValue<BigNumberish> | null,
      buyer?: PromiseOrValue<string> | null,
      fromIndex?: null,
      toIndex?: null,
      leftTickets?: null
    ): BuyTicketsEventFilter;
    BuyTickets(
      raffleId?: PromiseOrValue<BigNumberish> | null,
      buyer?: PromiseOrValue<string> | null,
      fromIndex?: null,
      toIndex?: null,
      leftTickets?: null
    ): BuyTicketsEventFilter;

    "ChooseWinner(uint256,address,uint256,uint256)"(
      raffleId?: PromiseOrValue<BigNumberish> | null,
      winner?: PromiseOrValue<string> | null,
      winnerTicketIndex?: null,
      settlement?: null
    ): ChooseWinnerEventFilter;
    ChooseWinner(
      raffleId?: PromiseOrValue<BigNumberish> | null,
      winner?: PromiseOrValue<string> | null,
      winnerTicketIndex?: null,
      settlement?: null
    ): ChooseWinnerEventFilter;

    "ClaimAllNfts(address,uint256[])"(
      claimer?: PromiseOrValue<string> | null,
      raffleIds?: null
    ): ClaimAllNftsEventFilter;
    ClaimAllNfts(
      claimer?: PromiseOrValue<string> | null,
      raffleIds?: null
    ): ClaimAllNftsEventFilter;

    "ClaimBalance(address,uint256,uint256)"(
      claimer?: PromiseOrValue<string> | null,
      amount?: null,
      afterBalance?: null
    ): ClaimBalanceEventFilter;
    ClaimBalance(
      claimer?: PromiseOrValue<string> | null,
      amount?: null,
      afterBalance?: null
    ): ClaimBalanceEventFilter;

    "ClaimNft(address,uint256)"(
      claimer?: PromiseOrValue<string> | null,
      raffleId?: PromiseOrValue<BigNumberish> | null
    ): ClaimNftEventFilter;
    ClaimNft(
      claimer?: PromiseOrValue<string> | null,
      raffleId?: PromiseOrValue<BigNumberish> | null
    ): ClaimNftEventFilter;

    "DeListNft(address)"(nftCa?: null): DeListNftEventFilter;
    DeListNft(nftCa?: null): DeListNftEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "ListNft(address,address,uint256)"(
      nftCa?: null,
      creator?: null,
      creatorFeeNumerator?: null
    ): ListNftEventFilter;
    ListNft(
      nftCa?: null,
      creator?: null,
      creatorFeeNumerator?: null
    ): ListNftEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "RegisterRaffle(uint256,uint256,address,uint256,uint256,uint256,address)"(
      raffleId?: PromiseOrValue<BigNumberish> | null,
      tokenId?: null,
      nftCa?: null,
      ticketPrice?: null,
      totalTickets?: null,
      endTime?: null,
      seller?: PromiseOrValue<string> | null
    ): RegisterRaffleEventFilter;
    RegisterRaffle(
      raffleId?: PromiseOrValue<BigNumberish> | null,
      tokenId?: null,
      nftCa?: null,
      ticketPrice?: null,
      totalTickets?: null,
      endTime?: null,
      seller?: PromiseOrValue<string> | null
    ): RegisterRaffleEventFilter;

    "SetCreatorInfo(address,uint256)"(
      creator?: null,
      creatorFeeNumerator?: null
    ): SetCreatorInfoEventFilter;
    SetCreatorInfo(
      creator?: null,
      creatorFeeNumerator?: null
    ): SetCreatorInfoEventFilter;

    "SetFeeNumerator(uint256)"(feeNumerator?: null): SetFeeNumeratorEventFilter;
    SetFeeNumerator(feeNumerator?: null): SetFeeNumeratorEventFilter;

    "SetMaxTicketAmount(uint256)"(amount?: null): SetMaxTicketAmountEventFilter;
    SetMaxTicketAmount(amount?: null): SetMaxTicketAmountEventFilter;

    "SetMinTicketPrice(uint256)"(price?: null): SetMinTicketPriceEventFilter;
    SetMinTicketPrice(price?: null): SetMinTicketPriceEventFilter;

    "WithdrawFee(address,uint256)"(
      to?: PromiseOrValue<string> | null,
      amount?: null
    ): WithdrawFeeEventFilter;
    WithdrawFee(
      to?: PromiseOrValue<string> | null,
      amount?: null
    ): WithdrawFeeEventFilter;
  };

  estimateGas: {
    buyTickets(
      raffleId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    buyer(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    chooseWinner(
      raffleId: PromiseOrValue<BigNumberish>,
      salt: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    claimAllNfts(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    claimBalance(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    claimNftByIndex(
      index: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    claimNftForFailedSeller(
      raffleId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    claimableBalance(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimableNft(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    creatorInfo(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deListNft(
      nftCa: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    feeBox(overrides?: CallOverrides): Promise<BigNumber>;

    feeNumerator(overrides?: CallOverrides): Promise<BigNumber>;

    feeTo(overrides?: CallOverrides): Promise<BigNumber>;

    getClaimableNftsLength(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTicketOwnerByIndex(
      raffleId: PromiseOrValue<BigNumberish>,
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      feeNumerator_: PromiseOrValue<BigNumberish>,
      maxTicketAmount_: PromiseOrValue<BigNumberish>,
      minTicketPrice_: PromiseOrValue<BigNumberish>,
      feeTo_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isListed(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "listNft(address,address,uint8)"(
      nftCa: PromiseOrValue<string>,
      creator: PromiseOrValue<string>,
      creatorFeeNumerator: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "listNft(address)"(
      nftCa: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    maxTicketAmount(overrides?: CallOverrides): Promise<BigNumber>;

    minTicketPrice(overrides?: CallOverrides): Promise<BigNumber>;

    onERC721Received(
      operator: PromiseOrValue<string>,
      from: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    raffles(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerRaffle(
      nftCa: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      totalTickets: PromiseOrValue<BigNumberish>,
      ticketPrice: PromiseOrValue<BigNumberish>,
      minute: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setCreatorInfo(
      nftCa: PromiseOrValue<string>,
      creator: PromiseOrValue<string>,
      creatorFeeNumerator: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setFeeNumerator(
      feeNumerator_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setFeeTo(
      feeTo_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMaxTicketAmount(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMinTicketPrice(
      price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawFee(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    buyTickets(
      raffleId: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    buyer(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    chooseWinner(
      raffleId: PromiseOrValue<BigNumberish>,
      salt: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    claimAllNfts(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    claimBalance(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    claimNftByIndex(
      index: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    claimNftForFailedSeller(
      raffleId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    claimableBalance(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claimableNft(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    creatorInfo(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deListNft(
      nftCa: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    feeBox(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    feeNumerator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    feeTo(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getClaimableNftsLength(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTicketOwnerByIndex(
      raffleId: PromiseOrValue<BigNumberish>,
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      feeNumerator_: PromiseOrValue<BigNumberish>,
      maxTicketAmount_: PromiseOrValue<BigNumberish>,
      minTicketPrice_: PromiseOrValue<BigNumberish>,
      feeTo_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isListed(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "listNft(address,address,uint8)"(
      nftCa: PromiseOrValue<string>,
      creator: PromiseOrValue<string>,
      creatorFeeNumerator: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "listNft(address)"(
      nftCa: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    maxTicketAmount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    minTicketPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onERC721Received(
      operator: PromiseOrValue<string>,
      from: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    raffles(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registerRaffle(
      nftCa: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      totalTickets: PromiseOrValue<BigNumberish>,
      ticketPrice: PromiseOrValue<BigNumberish>,
      minute: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setCreatorInfo(
      nftCa: PromiseOrValue<string>,
      creator: PromiseOrValue<string>,
      creatorFeeNumerator: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setFeeNumerator(
      feeNumerator_: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setFeeTo(
      feeTo_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMaxTicketAmount(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMinTicketPrice(
      price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawFee(
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
