/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface EventTestInterface extends utils.Interface {
  functions: {
    "test()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "test"): FunctionFragment;

  encodeFunctionData(functionFragment: "test", values?: undefined): string;

  decodeFunctionResult(functionFragment: "test", data: BytesLike): Result;

  events: {
    "Test(uint256,string,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Test"): EventFragment;
}

export interface TestEventObject {
  _uint: BigNumber;
  _string: string;
  blockNumber: BigNumber;
}
export type TestEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  TestEventObject
>;

export type TestEventFilter = TypedEventFilter<TestEvent>;

export interface EventTest extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EventTestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    test(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  test(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    test(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "Test(uint256,string,uint256)"(
      _uint?: null,
      _string?: null,
      blockNumber?: null
    ): TestEventFilter;
    Test(_uint?: null, _string?: null, blockNumber?: null): TestEventFilter;
  };

  estimateGas: {
    test(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    test(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
