/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as attackSol from "./Attack.sol";
export type { attackSol };
import type * as testTokens from "./TestTokens";
export type { testTokens };
import type * as undefined from "./Undefined";
export type { undefined };
export type { EventTest } from "./EventTest";
export type { UndefinedUtil } from "./UndefinedUtil";
